export enum ActionType {
  READ_ENTITY = "READ_ENTITY",
  UPDATE_ENTITY = "UPDATE_ENTITY",
  GENERATE_DOCUMENT = "GENERATE_DOCUMENT",
  NOTIFY = "NOTIFY",
  LOG_ACTION = "LOG_ACTION",
  CREATE_ENTITY="CREATE_ENTITY",
  DELETE_ENTITY="DELETE_ENTITY",
  MULTI_READ_ENTITY = "MULTI_READ_ENTITY",
  MULTI_READ_DOCUMENT = "MULTI_READ_DOCUMENT",
  AGGREGATE_ENTITY = "AGGREGATE_ENTITY",
  KNOWLEDGE_QUERY = "KNOWLEDGE_QUERY",
}